ag-ui-protocol/ag-ui

- docs/concepts/events.mdx
The table describing the properties of the [Custom event](https://docs.ag-ui.com/concepts/events#custom) is duplicated. This commit removes it.
> docs: remove duplicate custom event properties table

- typescript-sdk/integrations/vercel-ai-sdk/package.json
- typescript-sdk/pnpm-lock.yaml
Moves `@ag-ui/client` package to dependencies instead of peerDependecies inside `vercel-ai-sdk` integration to prevent build error.
Fixes: https://github.com/ag-ui-protocol/ag-ui/issues/67
> chore(typescipt-sdk/vercel-ai-sdk): moves @ag-ui/client to dependencies

- typescript-sdk/integrations/langgraph/src/index.ts
Exporting some of the types so they can be referenced when the agent is extended
> fix: export types related to langgraph agent

- typescript-sdk/integrations/langgraph/package.json
Force rxjs version and langgraph dependencies when the langgraph integration is used
> fix: use more explicit dependencies on the langgraph version

- python-sdk/ag_ui/core/events.py
- python-sdk/ag_ui/core/types.py
- python-sdk/tests/test_encoder.py
- python-sdk/tests/test_events.py
- python-sdk/tests/test_types.py
Set the event type and message role using pydantic Field and disable setting in the constructor to help prevent accidental misuse while reducing unnecessary boilerplate code.
Replace Role type alias with an Enum to eliminate repeating string literals and align with EventType.
Use Field(min_length=1) to validate TextMessageContentEvent delta, simplifying the code.
Fixes #41
> chore(python-sdk): literal defaults

- python-sdk/ag_ui/core/events.py
Add type literals for the new event types in the Python SDK, so users don't have to manually set the type field when creating event instances.
> chore(python-sdk): add type literals for new events

- typescript-sdk/integrations/agno/package.json
- typescript-sdk/integrations/langgraph/package.json
- typescript-sdk/integrations/mastra/package.json
- typescript-sdk/integrations/middleware-starter/package.json
- typescript-sdk/integrations/server-starter-all-features/package.json
- typescript-sdk/integrations/server-starter/package.json
- typescript-sdk/integrations/vercel-ai-sdk/package.json
- typescript-sdk/package.json
- typescript-sdk/packages/cli/package.json
- typescript-sdk/packages/client/package.json
- typescript-sdk/packages/client/tsup.config.ts
- typescript-sdk/packages/core/package.json
- typescript-sdk/packages/core/tsup.config.ts
- typescript-sdk/packages/encoder/package.json
- typescript-sdk/packages/encoder/tsup.config.ts
- typescript-sdk/packages/proto/package.json
- typescript-sdk/packages/proto/tsup.config.ts
Due to the way pnpm runs scripts in parallel, some packages were not ready when others tried to access them, leading to random build failures.
Fixes applied to eliminate race conditions:
- Disable clean in tsup config files
- Use the same clean method across all packages
Also:
- Add clean script to the root package.json for consistency
- Disable minify when watch is enabled for performance
Fixes #59
> fix(typescript-sdk): random build failures

- typescript-sdk/.gitignore
- typescript-sdk/apps/dojo/package.json
- typescript-sdk/apps/dojo/src/agents.ts
- typescript-sdk/apps/dojo/src/app/[integrationId]/feature/agentic_chat/page.tsx
- typescript-sdk/apps/dojo/src/app/[integrationId]/feature/agentic_generative_ui/page.tsx
- typescript-sdk/apps/dojo/src/app/[integrationId]/feature/human_in_the_loop/page.tsx
- typescript-sdk/apps/dojo/src/app/[integrationId]/feature/predictive_state_updates/page.tsx
- typescript-sdk/apps/dojo/src/config.ts
- typescript-sdk/apps/dojo/src/menu.ts
- typescript-sdk/integrations/crewai/python/ag_ui_crewai/examples/predictive_state_updates.py
- typescript-sdk/integrations/langgraph/examples/agents/predictive_state_updates/agent.py
- typescript-sdk/integrations/langgraph/python/ag_ui_langgraph/examples/agents/predictive_state_updates.py
- typescript-sdk/integrations/pydantic-ai/.npmignore
- typescript-sdk/integrations/pydantic-ai/README.md
- typescript-sdk/integrations/pydantic-ai/jest.config.js
- typescript-sdk/integrations/pydantic-ai/package.json
- typescript-sdk/integrations/pydantic-ai/src/index.ts
- typescript-sdk/integrations/pydantic-ai/tsconfig.json
- typescript-sdk/integrations/pydantic-ai/tsup.config.ts
- typescript-sdk/integrations/server-starter-all-features/server/python/example_server/predictive_state_updates.py
- typescript-sdk/pnpm-lock.yaml
Add support for the Pydantic AI integration.
Add missing background change confirmation.
Increase agentic generation ui page size to allow it to display results from the Pydantic AI integration better.
Add a description for the human in the loop generate_task_steps tool, so the Pydantic AI example works as expected.
Merge write_document and confirm_changes tool into one, which allows it work correctly with the Pydantic AI example, without the need for the agent to perform two separate tool calls.
Sort the features, so they are easier to find when reading the code and implementing new integrations.
Fixes: #5
> feat: Pydantic AI support

- typescript-sdk/apps/dojo/src/components/layout/main-layout.tsx
useSearchParams was brought into the main layout in https://github.com/ag-ui-protocol/ag-ui/pull/190 but requires the component calling it to be inside a Suspense boundary. I moved it down into a "MaybeSidebar" that uses the hook and optionally renders the sidebar, and added it inside of a Suspense inside the main layout render.
> Fix build by wrapping sidebar in a suspense

- .github/workflows/test.yml
- typescript-sdk/apps/dojo/package.json
- typescript-sdk/pnpm-lock.yaml
@mastra/core got bumped in the integration but not here, and some other libs needed bumped as well (but not all!)
Edit: Also run a full build when running tests in CI so we don't keep bumping into the dojo breaking
> Bump some mastra versions in dojo to align with types in mastra integration

- docs/quickstart/clients.mdx
This fixes a broken link in the docs caused by a small typo in the URL for CopilotKit.
> Fix typo in CopilotKit link

- typescript-sdk/integrations/langgraph/python/pyproject.toml
release v0.0.5 of langgraph python fastapi integration, which includes:
LangGraph v0.5.x & v0.6.x support
Time travel (regenerate) and a bunch more items
> chore: release v0.0.5 of langgraph python fastapi integration

- typescript-sdk/integrations/mastra/example/src/mastra/index.ts
It looks like Mastra changed the default host to localhost, which breaks render hosting
> use 0.0.0.0 as host for mastra example since default changed

- typescript-sdk/apps/dojo/package.json
- typescript-sdk/apps/dojo/src/app/[integrationId]/feature/layout.tsx
- typescript-sdk/apps/dojo/src/app/globals.css
- typescript-sdk/apps/dojo/src/components/demo-list/demo-list.tsx
- typescript-sdk/apps/dojo/src/components/layout/main-layout.tsx
- typescript-sdk/apps/dojo/src/components/layout/viewer-layout.tsx
- typescript-sdk/apps/dojo/src/components/sidebar/sidebar.tsx
- typescript-sdk/apps/dojo/src/styles/typography.css
- typescript-sdk/apps/dojo/tailwind.config.ts
- typescript-sdk/pnpm-lock.yaml
This PR brings redesign of the dojo with some colors and fonts and a bunch of good stuff
> chore: dojo redesign

- typescript-sdk/integrations/langgraph/python/ag_ui_langgraph/agent.py
- typescript-sdk/integrations/langgraph/python/pyproject.toml
- typescript-sdk/integrations/langgraph/src/agent.ts
Fixing LG regenerate mechanism: When resending the message, send it along with all the state it had at that point
> fix: include payload with regenerated message

- README.md
While the Java SDK is still under development, a seperate github repository has been set up for faster dev
> Fix: updated README.md with pointer towards the Java SDK

- typescript-sdk/apps/dojo/e2e/playwright.config.ts
Something gets weird with the tests running in parallel, especially in CI. For now making them serial so people and PRs can get unblocked while I dig in
> deparallelize the tests in CI for now

- typescript-sdk/apps/dojo/scripts/generate-content-json.ts
Since the ag-ui example for pydantic-ai now lives in the repo, we can reference the local files.
> use local files for pydantic example

- typescript-sdk/integrations/langgraph/python/ag_ui_langgraph/agent.py
- typescript-sdk/integrations/langgraph/src/agent.ts
We seem to have a bug with steps not being properly closed in LangGraph integrations. This is a fix
> fix: close off dangling steps by properly tracking open ones

- typescript-sdk/packages/core/src/events.ts
Modern AI models like DeepSeek and Doubao support a "thinking" process where they can expose their internal reasoning before generating the final response. This thinking process provides valuable insights into the model's decision-making and improves transparency.
When these models send THINK_START events,`typescript-sdk/packages/core/src/events.ts` was failing with `invalid_union_discriminator` errors. And if not send THINK_START, `typescript-sdk/packages/client/src/verify/verify.ts` will raise error: 
> Cannot send 'THINKING_TEXT_MESSAGE_START' event: A thinking step is not in progress. Create one with 'THINKING_START' first.
This caused the zod validation to reject any THINKING_START or THINKING_END events, breaking the thinking flow entirely.
Added the missing schemas to the …
> Fix: Add Support for Model Thinking Process Events

- typescript-sdk/packages/client/src/agent/__tests__/legacy-bridged.test.ts
- typescript-sdk/packages/client/src/legacy/convert.ts
When a RUN_FINISHED event comes in, we convert it to a legacy AgentStateMessage, even if state is empty (I'm not convinced that it is ever not empty). This causes things like pedantic's integration to fail when a user sends a message that does not affect state, since the integration doesn't send anything back.
> If state is empty on run_finished event, don't trigger a state update

- typescript-sdk/integrations/langgraph/package.json
- typescript-sdk/pnpm-lock.yaml
There could be a mismatch between the version considered by the integrations (LG in this example) and the core packages (client, core).
This PR sets the LG integration to use the core packages as peer dependencies, so the mismatch could be easily resolved
> fix: use peer and dev dependencies to prevent version locks for consumers

- README.md
Updated AG-UI resources and demo links for various frameworks.
Use dojo.ag-ui.com for all demo links.
> Updated demo and docs links

- typescript-sdk/integrations/langgraph/python/ag_ui_langgraph/agent.py
- typescript-sdk/integrations/langgraph/python/ag_ui_langgraph/utils.py
Some events might not be JSON serializable.
This PR creates a fix for that
> fix: ensure serializable raw events attached to LG AGUI events

- typescript-sdk/packages/client/src/run/__tests__/http-request.test.ts
- typescript-sdk/packages/client/src/run/http-request.ts
With the HTTP Agent (which some of the integrations are based on) we do not surface simple HTTP errors like 404 or 500.
This PR adds that
> fix: surface HTTP errors when using http requests

- typescript-sdk/integrations/langgraph/python/ag_ui_langgraph/agent.py
- typescript-sdk/integrations/langgraph/python/ag_ui_langgraph/types.py
- typescript-sdk/integrations/langgraph/src/agent.ts
- typescript-sdk/integrations/langgraph/src/types.ts
Some models will not stream function calls. This means using these models with LangGraph will not yield the expected tool events.
This PR fixes this issue
> feat: return tool call events for models that does not stream tool calls

- typescript-sdk/integrations/langgraph/src/agent.ts
A common technique to avoid running frontend tools in a ReAct agent, is by doing something like this:
```
if (!tools || tools.every((tool) => tool.name !== toolCallName)) {
```
However, the tool name seems to be missing. This PR is about adding it
> fix: include the tool name on the top level per returned frontend tool

- typescript-sdk/integrations/adk-middleware/README.md
Not sure how this got copied over but it's clearly wrong
> Revert copying pydantic readme over adk readme

- typescript-sdk/packages/client/src/run/http-request.ts
- typescript-sdk/packages/client/src/transform/__tests__/http.test.ts
- typescript-sdk/packages/client/src/transform/http.ts
Abort errors when using `abortRun` are expected. However, the abort controller will throw an error (default behaviour). These should be silenced as they fail the server running a runtime against AGUI HTTP agent
> fix: silence abort error in http agent
